[package]
name = "topic-api"
version = "0.1.0"
authors.workspace = true
description.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
dto.workspace = true
serde.workspace = true
serde_json.workspace = true
slog.workspace = true
by-axum.workspace = true
easy-dynamodb.workspace = true

tokio = { version = "1.40.0", features = ["full"] }
tower = "0.5.1"

[features]
default = []
lambda = ["by-axum/lambda"]
