[workspace]
members = ["packages/main-ui", "packages/dto", "packages/main-api", "packages/dioxus-popup", "packages/google-wallet"]
resolver = "2"

[workspace.package]
authors = ["Biyard"]
description = "DemocraSee"
edition = "2021"
repository = "https://github.com/biyard/democrasee"

[workspace.dependencies]
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.133"
slog = "2.7.0"
by-axum = { version = "0.1.7" }
easy-dynamodb = "0.1.6"
dto = { path = "./packages/dto" }
reqwest = { version = "0.12.5", features = ["blocking", "json", "multipart"] }

[profile]

[profile.wasm-dev]
inherits = "dev"
opt-level = 1

[profile.server-dev]
inherits = "dev"

[profile.android-dev]
inherits = "dev"
