[workspace]
members = ["packages/main-ui", "packages/dto", "packages/main-api", "packages/dioxus-popup", "packages/google-wallet", "packages/dioxus-oauth", "examples/oauth", "packages/dioxus-translate-macro", "packages/dioxus-translate", "packages/dioxus-translate-types"]
resolver = "2"

[workspace.package]
authors = ["Biyard"]
description = "DemocraSee"
edition = "2021"
repository = "https://github.com/biyard/democrasee"
license = "MIT"

[workspace.dependencies]
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.133"
slog = "2.7.0"
by-axum = { path="../rust-sdk/packages/by-axum", version = "0.2.0" }
easy-dynamodb = { version = "0.1.7" }
dto = { path = "./packages/dto" }
reqwest = { version = "0.12.5", features = ["blocking", "json", "multipart"] }
dioxus = { version = "0.6.1" }

[profile]

[profile.wasm-dev]
inherits = "dev"
opt-level = 1

[profile.server-dev]
inherits = "dev"

[profile.android-dev]
inherits = "dev"
