[package]
name = "dioxus-translate-macro"
version = "0.1.0"
authors.workspace = true
description.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
proc-macro2 = "1.0.92"
quote = "1.0.38"
syn = "2.0.95"
dioxus-translate-types = { path = "../dioxus-translate-types" }

[lib]
proc-macro = true

[features]
default = []
ko = []