[package]
name = "dto"
version = "0.1.0"
authors.workspace = true
description.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
serde.workspace = true
serde_json = { workspace = true, optional = true }
by-axum = { workspace = true, optional = true }
slog = { workspace = true, optional = true }
easy_dynamodb = { workspace = true, optional = true }


[features]
default = []
server = ["by-axum", "serde_json", "slog", "easy_dynamodb"]
