[package]
name = "dto"
version = "0.1.0"
authors.workspace = true
description.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
dioxus-translate.workspace = true
by-types.workspace = true
by-macros.workspace = true
by-axum = { workspace = true, optional = true }
rest-api.workspace = true

serde.workspace = true
serde_json = { workspace = true }
sqlx = { workspace = true, optional = true }
reqwest.workspace = true

chrono = "0.4.39"
base64 = "0.22.1"
ring = "0.17.8"
simple_asn1 = "0.6.2"
candid = "0.10.11"
untrusted = "0.9.0"
serde_urlencoded = "0.7.1"
num-format = "0.4.4"
schemars = "0.8.21"
tracing = "0.1.41"
validator = { version = "0.20.0", features = ["derive"] }
lazy_static = "1.5.0"
regex = "1.11.1"
bigdecimal = "0.4.7"

[features]
web = ["dioxus-translate/web"]
server = ["by-axum", "by-macros/server", "sqlx", "by-types/server"]
