[package]
name = "dto"
version = "0.1.0"
authors.workspace = true
description.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
serde.workspace = true
serde_json = { workspace = true, optional = true }
by-axum = { workspace = true, optional = true }
slog = { workspace = true, optional = true }
easy-dynamodb = { workspace = true, optional = true }
chrono = "0.4.39"
base64 = "0.22.1"
ring = "0.17.8"
simple_asn1 = "0.6.2"
candid = "0.10.11"


[features]
default = []
server = ["by-axum", "serde_json", "slog", "easy-dynamodb"]
