[package]
name = "dioxus-translate"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
description = "Libraries for internalization on Dioxus"
license = "MIT"
keywords = ["dioxus", "web", "i18n", "translate"]
repository = "https://github.com/biyard/democrasee/tree/main/packages/dioxus-translate"

[dependencies]
dioxus-translate-macro = { path = "../dioxus-translate-macro", version = "0.1.0" }
dioxus-translate-types = { path = "../dioxus-translate-types", version = "0.1.0" }
serde.workspace = true
web-sys = { version = "0.3.76", optional = true }

[features]
web = ["web-sys"]
ko = ["dioxus-translate-types/ko","dioxus-translate-macro/ko"]
