[package]
name = "dioxus-translate-types"
version = "0.1.0"
authors.workspace = true
description.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]

[features]
ko = []