[package]
name = "google-wallet"
version = "0.1.0"
authors.workspace = true
description.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
base64 = "0.22.1"
dioxus = { version = "0.6.0" }
dioxus-oauth = { version = "0.6.1", features = [ "web" ], optional = true }
gloo-storage = "0.3.0"
reqwest = { workspace = true, features = ["blocking", "json"] }
serde.workspace = true

[features]
default = []
web = ["dioxus/web", "dioxus-oauth"]
