[package]
name = "main-ui"
version = "0.2.1"
authors.workspace = true
description.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
reqwest.workspace = true
dto.workspace = true
dioxus = { version = "0.6.0", features = ["router"] }

dioxus-aws = { version = "0.6.13" }
dioxus-web = { version = "0.6.0", features = [], optional = true }
dioxus-logger = { version = "0.5.0" }
tracing = { version = "0.1.40" }

wasm-bindgen = { version = "0.2.99", optional = true }
wasm-bindgen-futures = { version = "0.4.49", optional = true }
web-sys = { version = "0.3.72", features=["Navigator"], optional = true}
serde = "1.0.216"
num-format = "0.4.4"

dioxus-popup = { path = "../dioxus-popup" }
dioxus-sdk = { version = "0.6.0", features = ["window_size"], optional = true }

[features]
default = []
web = ["web-only", "dioxus-aws/web"]
web-only = ["web-sys", "wasm-bindgen", "wasm-bindgen-futures", "dioxus-aws/web-only", "dioxus-web", "dioxus-sdk"]
server = ["dioxus-aws/server"]
lambda = ["server", "dioxus-aws/lambda"]
