[package]
name = "fetcher"
version = "0.1.0"
authors.workspace = true
description.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
dto = { workspace = true, features = ["server"] }
serde.workspace = true
serde_json.workspace = true
bdk = { workspace = true, features = ["be"] }
tokio = { version = "1.40.0", features = ["full"] }
tracing = "0.1.41"
scraper = "0.23.1"
