name: Dev deploy

on:
  push:
    branches:
      - dev
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  main-ui:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          ssh-key: ${{ secrets.PULL_KEY_REPO }}

      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy, rustfmt
          target: wasm32-unknown-unknown
          toolchain: stable

      - name: Install dioxus-cli
        run: |
          cargo install dioxus-cli --version 0.6.0
          cargo install toml-cli

      - name: Cache builder
        id: main-ui-build-cache
        uses: actions/cache@v3
        with:
          key: main-ui-build-cache
          path: |
            target

      - name: Cache builder
        id: main-ui-artifacts
        uses: actions/cache@v3
        with:
          key: main-ui-artifacts
          path: |
            .build/main-ui


      - name: Checking violate
        env:
          REGION: ap-northeast-2
          ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SERVICE: main-ui
        run: |
          dx check -p $SERVICE

      - name: Deploy APIs
        env:
          REGION: ap-northeast-2
          ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          ENV: dev
          SERVICE: main-ui
          DOMAIN: dev.democrasee.me
          API_PREFIX: /api
          ENABLE_S3: true
          ENABLE_FARGATE: false
          ENABLE_DYNAMO: true
          ENABLE_LAMBDA: true
        run: |
          npm i -g aws-cdk tailwindcss
          make deploy-web-if-needed

  main-api:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          ssh-key: ${{ secrets.PULL_KEY_REPO }}

      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy, rustfmt
          target: wasm32-unknown-unknown
          toolchain: stable

      - name: Install dioxus-cli
        run: |
          cargo install toml-cli

      - name: Cache builder
        id: topic-api-build-cache
        uses: actions/cache@v3
        with:
          key: topic-api-build-cache
          path: |
            target

      - name: Cache builder
        id: topic-api-artifacts
        uses: actions/cache@v3
        with:
          key: topic-api-artifacts
          path: |
            .build/topic-api

      - name: Deploy APIs
        env:
          REGION: ap-northeast-2
          ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          ENV: dev
          SERVICE: main-api
          DOMAIN: api.dev.democrasee.me
          ENABLE_S3: false
          ENABLE_FARGATE: false
          ENABLE_DYNAMO: false
          ENABLE_LAMBDA: true
        run: |
          npm i -g aws-cdk
          make deploy-if-needed

  create-release-pr:
    runs-on: ubuntu-latest
    needs:
      [
        main-ui,
      ]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          ssh-key: ${{ secrets.PULL_KEY_REPO }}
      - name: Git pr release action
        uses: grassedge/git-pr-release-action@v1.0
        with:
          base: main
          head: dev
          token: ${{ secrets.GITHUB_TOKEN }}
