[package]
name = "main-api"
version = "0.7.10"
authors.workspace = true
description.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
dto = { workspace = true, features = ["server"] }
serde.workspace = true
serde_json.workspace = true
slog.workspace = true

bdk = { workspace = true, features = ["be"] }

tokio = { version = "1.40.0", features = ["full"] }
tower = "0.5.1"
chrono = "0.4.39"
uuid = { version = "1.10.1", features = ["v4"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
validator = "0.20.0"
select = "0.6.0"
sxd-xpath = "0.4.2"
sxd-document = "0.3.2"
scraper = "0.23.1"

[features]
default = []
lambda = ["bdk/lambda"]
