[package]
name = "main-api"
version = "0.7.3"
authors.workspace = true
description.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
dto = { workspace = true, features = [ "server" ] }
serde.workspace = true
serde_json.workspace = true
slog.workspace = true
by-axum.workspace = true
easy-dynamodb.workspace = true
dioxus-translate = { path = "../dioxus-translate", features = ["ko"] }

tokio = { version = "1.40.0", features = ["full"] }
tower = "0.5.1"
chrono = "0.4.39"
reqwest.workspace = true
uuid = { version = "1.10.1", features = ["v4"] }
rest-api = "0.1.1"

[features]
default = []
lambda = ["by-axum/lambda"]
